// <auto-generated />
namespace TrainChat.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropRolesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropRolesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201512071555083_DropRolesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
